version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: sea_jobs_postgres
    environment:
      POSTGRES_DB: sea_jobs_db
      POSTGRES_USER: sea_jobs_user
      POSTGRES_PASSWORD: phixystuph
    ports:
      - "5432:5432"
    volumes:
      - sea_jobs_postgres_data:/var/lib/postgresql/data

volumes:
  sea_jobs_postgres_data: